# Generated by Django 3.2.16 on 2024-11-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_publlished',
            new_name='is_published',
        ),
    ]
